### ISSUE TITLE
jvm implementation fails at test 3

### ISSUE THREAD

**Issue by ghost** [RCasatta/schnorr_edu#1]
Hi i'm writing a jvm implementation in scala. Im having a problem signing the test vector number 3. Did some digging and found the culprit

https://github.com/floreslorca/fp-schnorr/blob/master/src/main/scala/fp/schnorr/BIPSchnorrSigner.scala#L68

And here is what happens:

https://gist.github.com/floreslorca/e76317f0769c1994a1c12c77a787ac5f

It occurs when trying to get mod with two particularly large numbers. I also manage to replicate this issue in Go. The python implementation produces a different number. I looked at your code but im not very familiar with rust. what i could see is that there was no mod operation at the end of your `point_sum` implementation. did you run with this issue as well?

**Comment by RCasatta** [comment]
Hi,

I didn't encounter the same issue.

You don't see the modulo operation at the end of the `point_sum` operation because it's always executed in the multiplication of the two `ScalarP` struct.
see 
https://github.com/RCasatta/schnorr_edu/blob/master/src/scalar/scalar_p.rs#L75 and
https://github.com/RCasatta/schnorr_edu/blob/master/src/scalar/scalar_p.rs#L24

**Comment by ghost** [comment]
Thanks for reaching out. I figured what the problem on my implementation was. turns out the BigInteger uses `this.mod(that)` instead of % to do this kind of big int operation
